### ISSUE TITLE
Resolver is not a function

### ISSUE THREAD

**Issue by sniper365** [wilddip/ff-io#2]
Hi

While implementing this module in express.js, I got bellow error

```
error - TypeError: resolver is not a function
    at Object.apiResolver (D:\2-Bohdan\1-coinchili\node_modules\next\dist\server\api-utils\node.js:179:15)
    at DevServer.runApi (D:\2-Bohdan\1-coinchili\node_modules\next\dist\server\next-server.js:381:27)
    at async Object.fn (D:\2-Bohdan\1-coinchili\node_modules\next\dist\server\base-server.js:488:37)
    at async Router.execute (D:\2-Bohdan\1-coinchili\node_modules\next\dist\server\router.js:213:36)
    at async DevServer.run (D:\2-Bohdan\1-coinchili\node_modules\next\dist\server\base-server.js:621:29)
    at async DevServer.run (D:\2-Bohdan\1-coinchili\node_modules\next\dist\server\dev\next-dev-server.js:533:20)    
    at async DevServer.handleRequest (D:\2-Bohdan\1-coinchili\node_modules\next\dist\server\base-server.js:317:20) {
  page: '/api/fixedfloat'
}

```
router.js
```
const express = require('express');
const router = express.Router();

const request = require('superagent');
const async = require('async');

const FixedFloat = require('fixedfloat-api');

const fixed = new FixedFloat('apikey', 'secretkey')

router.get('/api/fixedfloat', (req, res) => {
  request
    .get(fixed.getPrice('0.1 BTC', 'ETH'))  
    .end((err, response) => {
      if (err) {
        return res.status(500).json(err);
      }
      console.log('---------fixedfloat---------', response.body)
      res.status(200).json(response.body);
    });
})
```

I am not sure why this is happening.. Could you fix me?

**Comment by wilddip** [comment]
It looks like this is happening on the front-end (`node_modules\next`)
